version: '2.2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8050
    volumes:
      - .:/CODE
    ports:
      - 8050:8050
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-e)(rr(7dca&!tpa-zhgcu+k_1m6ep%69@uy301!*x6=v8teb(i"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: