version: '2.2'
services:
  web:
    build: .
    command:  gunicorn django_project.wsgi -b 0.0.0.0:8050  # new
    volumes:
      - .:/CODE
    ports:
      - 8050:8050
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-e)(rr(7dca&!tpa-zhgcu+k_1m6ep%69@uy301!*x6=v8teb(i"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"  # new
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"  # new
      - "DJANGO_SECURE_HSTS_PRELOAD=False"  # new
      - "DJANGO_SESSION_COOKIE_SECURE=False"  # new
      - "DJANGO_CSRF_COOKIE_SECURE=False"  # new
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: